version: '3'

services:
  proxy:
    build: .
    ports:
      - "8080:8080"
      - "8000:8000"
    volumes:
      - ./certs:/app/certs
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=proxy_db
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=proxy_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 